include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable some overly strict rules
    avoid_print: false
    prefer_single_quotes: true
    use_super_parameters: false
    
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
