// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzPdku_WGSA0S1YjhejR8_-y8Jmby3Y6s',
    appId: '1:250735338958:web:c198e73f2a68772a15379f',
    messagingSenderId: '250735338958',
    projectId: 'healthsync-f3231',
    authDomain: 'healthsync-f3231.firebaseapp.com',
    storageBucket: 'healthsync-f3231.firebasestorage.app',
    measurementId: 'G-8M2SK67ZTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNvtZBDgkyo9omVkpepEmOWsO6M69KY4c',
    appId: '1:250735338958:android:e2a660afd5befd6115379f',
    messagingSenderId: '250735338958',
    projectId: 'healthsync-f3231',
    storageBucket: 'healthsync-f3231.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvfnnRUBi3wVc4Aq4qZYa99y6Mi_mXkBw',
    appId: '1:250735338958:ios:7c6984769394964d15379f',
    messagingSenderId: '250735338958',
    projectId: 'healthsync-f3231',
    storageBucket: 'healthsync-f3231.firebasestorage.app',
    iosClientId: '250735338958-ism4amvjgaorjaf09ihc1kmcuvhu9uq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvfnnRUBi3wVc4Aq4qZYa99y6Mi_mXkBw',
    appId: '1:250735338958:ios:7c6984769394964d15379f',
    messagingSenderId: '250735338958',
    projectId: 'healthsync-f3231',
    storageBucket: 'healthsync-f3231.firebasestorage.app',
    iosClientId: '250735338958-ism4amvjgaorjaf09ihc1kmcuvhu9uq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzPdku_WGSA0S1YjhejR8_-y8Jmby3Y6s',
    appId: '1:250735338958:web:019164600fe0ebef15379f',
    messagingSenderId: '250735338958',
    projectId: 'healthsync-f3231',
    authDomain: 'healthsync-f3231.firebaseapp.com',
    storageBucket: 'healthsync-f3231.firebasestorage.app',
    measurementId: 'G-JM9Q5LERYY',
  );
}
